table Inventory_ABC_Aging_By_Category_DC
	lineageTag: 0b414be0-8e5c-4b8a-a53f-fd34373d77b1

	column product_category
		dataType: string
		lineageTag: 45b1dd8f-54a8-4247-8c76-1e3dae859fc4
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column department
		dataType: string
		lineageTag: 153aadaf-7bd8-47c2-921b-78d4caacebf9
		summarizeBy: none
		sourceColumn: department

		annotation SummarizationSetBy = Automatic

	column center_id
		dataType: int64
		formatString: 0
		lineageTag: 7b049d70-11d2-4ec5-a6f1-3d5a292b6434
		summarizeBy: sum
		sourceColumn: center_id

		annotation SummarizationSetBy = Automatic

	column total_units
		dataType: int64
		formatString: 0
		lineageTag: 7b7cb689-d2a7-483e-bc00-08d8f6dcece8
		summarizeBy: sum
		sourceColumn: total_units

		annotation SummarizationSetBy = Automatic

	column sold_units
		dataType: int64
		formatString: 0
		lineageTag: 2cc0437e-c3a8-4c5d-8990-ac163515a217
		summarizeBy: sum
		sourceColumn: sold_units

		annotation SummarizationSetBy = Automatic

	column unsold_units
		dataType: int64
		formatString: 0
		lineageTag: b60a1f31-493a-44d8-8133-eb57b13859ea
		summarizeBy: sum
		sourceColumn: unsold_units

		annotation SummarizationSetBy = Automatic

	column frozen_capital
		dataType: double
		lineageTag: 09967eba-7f8c-48e6-99ed-336d1737661e
		summarizeBy: sum
		sourceColumn: frozen_capital

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column holding_cost_to_cutoff
		dataType: double
		lineageTag: d5c3665d-ca05-41b7-b6e4-1f148a9ec5d2
		summarizeBy: sum
		sourceColumn: holding_cost_to_cutoff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_holding_days_unsold
		dataType: double
		lineageTag: 4274cb34-76aa-47a7-8906-ba4405a7fd06
		summarizeBy: sum
		sourceColumn: avg_holding_days_unsold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aged_180_units
		dataType: int64
		formatString: 0
		lineageTag: fcda0f5f-9bff-4664-b656-5ed0f606a2e5
		summarizeBy: sum
		sourceColumn: aged_180_units

		annotation SummarizationSetBy = Automatic

	column aged_365_units
		dataType: int64
		formatString: 0
		lineageTag: 21b6fb97-8009-4044-b90e-c06abc3a3699
		summarizeBy: sum
		sourceColumn: aged_365_units

		annotation SummarizationSetBy = Automatic

	column aged_180_cost
		dataType: double
		lineageTag: 821388a0-599b-49d3-8372-246172414f50
		summarizeBy: sum
		sourceColumn: aged_180_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aged_365_cost
		dataType: double
		lineageTag: 55048d0b-02c1-4bfe-8271-4d2587abb071
		summarizeBy: sum
		sourceColumn: aged_365_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sell_through_pct
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0b8f82aa-23d2-49b8-8510-7ee7230760ae
		summarizeBy: sum
		sourceColumn: sell_through_pct

		annotation SummarizationSetBy = User

	column dc_name
		dataType: string
		lineageTag: 466a95c0-3549-410a-91ab-f00f5cdfe447
		summarizeBy: none
		sourceColumn: dc_name

		annotation SummarizationSetBy = Automatic

	column category_revenue
		dataType: double
		lineageTag: 2989e386-4038-4383-950e-d484d397124a
		summarizeBy: sum
		sourceColumn: category_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column category_gross_profit
		dataType: double
		lineageTag: 898d0d2a-d994-40fe-9990-dcddc86cd351
		summarizeBy: sum
		sourceColumn: category_gross_profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gross_margin_pct
		dataType: double
		lineageTag: eb8b0513-e8b2-4cab-b80b-4c2497907281
		summarizeBy: sum
		sourceColumn: gross_margin_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status_leakage_value
		dataType: double
		lineageTag: 7465c4e2-b22b-43d2-be00-d6ce0bf0c2ab
		summarizeBy: sum
		sourceColumn: status_leakage_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column category_quadrant
		dataType: string
		lineageTag: 1ed9eae4-a6aa-44e6-a659-168c489b0b66
		summarizeBy: none
		sourceColumn: category_quadrant

		annotation SummarizationSetBy = Automatic

	column category_revenue_share_pct
		dataType: double
		lineageTag: 29659ba2-4225-4c30-a4eb-7763c65c10e5
		summarizeBy: sum
		sourceColumn: category_revenue_share_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column category_cumulative_revenue_share_pct
		dataType: double
		lineageTag: d083690c-6b87-4abe-8d54-4b01c68e4c87
		summarizeBy: sum
		sourceColumn: category_cumulative_revenue_share_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column abc_class
		dataType: string
		lineageTag: 759467f9-ca0b-4105-abed-c77aca6005ca
		summarizeBy: none
		sourceColumn: abc_class

		annotation SummarizationSetBy = Automatic

	column inventory_action
		dataType: string
		lineageTag: 1dc31387-a27a-4c0e-9645-a5923057eda0
		summarizeBy: none
		sourceColumn: inventory_action

		annotation SummarizationSetBy = Automatic

	partition Inventory_ABC_Aging_By_Category_DC = m
		mode: import
		source =
				let
				    Source = fnLoadCsv("inventory_abc_aging_by_category_dc.csv"),
				    Typed = Table.TransformColumnTypes(Source, TypeMaps[InventoryAbcTypes], "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(Typed,{{"sell_through_pct", Percentage.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

